server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 600    #session配置，单位（秒），如果小于1分钟，则值是1分钟（最小生效值是1分钟），不设值是30分钟
#    context-path: /api  #配置根路径

spring:
  elasticsearch:
    jest:
      uris:
      - http://192.168.0.205:9200
      read-timeout: 5000
  redis:
    host: 192.168.0.104
    port: 6379
    password: '028911'
  session:
    store-type: redis  #这里用none、redis都行，配mongo也行，值是什么似乎都行，都写进redis里

  datasource:
    websvr:
      url: jdbc:mysql://192.168.0.104:3306/websvr_db
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: '028911'
    extra:
      url: jdbc:mysql://192.168.0.104:3306/extra_db
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: '028911'

  freemarker:
    template-loader-path: classpath:/templates  #设定ftl文件路径
    cache: false   #关闭缓存，及时刷新，上线生产环境为true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl


