server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8


spring:
  redis:
    host: localhost
    port: 6379
#    password: admin
  datasource:
    websvr:
      url: jdbc:mysql://192.168.0.104:3306/websvr_db
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: '028911'
    extra:
      url: jdbc:mysql://192.168.0.104:3306/extra_db
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: '028911'

  freemarker:
    template-loader-path: classpath:/templates  #设定ftl文件路径
    cache: false   #关闭缓存，及时刷新，上线生产环境为true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
